(() => {
  // <stdin>
  console.log("This site was generated by Hugo.");
  document.addEventListener("DOMContentLoaded", () => {
    const navList = document.querySelector(".nav-list");
    const modal = document.querySelector(".figure-modal");
    const modalImage = document.querySelector(".figure-modal-image");
    const modalClose = document.querySelector(".figure-close");
    const modalDownload = document.querySelector(".figure-download");
    const modalCode = document.querySelector(".figure-modal-code");
    if (!navList) {
      if (modal && modalImage && modalClose && modalDownload) {
        modalClose.addEventListener("click", () => {
          modal.classList.remove("is-open");
          modal.setAttribute("aria-hidden", "true");
          modalImage.removeAttribute("src");
          modalImage.removeAttribute("alt");
          modalDownload.removeAttribute("href");
        });
      }
      return;
    }
    navList.addEventListener("click", (event) => {
      if (event.target.closest(".post-figure")) {
        return;
      }
      const item = event.target.closest(".nav-item");
      if (!item || !navList.contains(item)) {
        return;
      }
      if (item.classList.contains("is-open")) {
        item.classList.remove("is-open");
        item.blur();
        return;
      }
      navList.querySelectorAll(".nav-item.is-open").forEach((openItem) => {
        openItem.classList.remove("is-open");
      });
      item.classList.add("is-open");
      item.focus();
    });
    navList.addEventListener("keydown", (event) => {
      if (event.key !== "Enter" && event.key !== " ") {
        return;
      }
      const item = event.target.closest(".nav-item");
      if (!item || !navList.contains(item)) {
        return;
      }
      event.preventDefault();
      item.click();
    });
    if (modal && modalImage && modalClose && modalDownload && modalCode) {
      navList.addEventListener("click", (event) => {
        const figure = event.target.closest(".post-figure");
        if (!figure) {
          return;
        }
        event.stopPropagation();
        const imageSrc = figure.currentSrc || figure.src;
        const codeLink = figure.dataset.link;
        modalImage.src = imageSrc;
        modalImage.alt = figure.alt || "";
        modalDownload.href = imageSrc;
        modalDownload.setAttribute("download", "");
        if (codeLink) {
          modalCode.href = codeLink;
          modalCode.style.display = "block";
        } else {
          modalCode.style.display = "none";
        }
        modal.classList.add("is-open");
        modal.setAttribute("aria-hidden", "false");
      });
      modal.addEventListener("click", (event) => {
        if (event.target === modal) {
          modalClose.click();
        }
      });
      document.addEventListener("keydown", (event) => {
        if (event.key === "Escape" && modal.classList.contains("is-open")) {
          modalClose.click();
        }
      });
      modalClose.addEventListener("click", () => {
        modal.classList.remove("is-open");
        modal.setAttribute("aria-hidden", "true");
        modalImage.removeAttribute("src");
        modalImage.removeAttribute("alt");
        modalDownload.removeAttribute("href");
        modalCode.removeAttribute("href");
      });
    }
  });
})();
